# Generated by Django 5.2.9 on 2026-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='boundary_wall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='built_up_area',
            field=models.PositiveIntegerField(blank=True, help_text='Built-up area in sq ft', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cabins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='conference_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='corner_plot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='frontage_width',
            field=models.FloatField(blank=True, help_text='Frontage width in feet', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('FURNISHED', 'Fully Furnished'), ('SEMI_FURNISHED', 'Semi Furnished'), ('UNFURNISHED', 'Unfurnished')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pantry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.FloatField(blank=True, help_text='Plot area in sq ft', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_length',
            field=models.FloatField(blank=True, help_text='Length in feet', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_width',
            field=models.FloatField(blank=True, help_text='Width in feet', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='BHK'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Square feet'),
        ),
        migrations.AlterField(
            model_name='property',
            name='subcategory',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'House / Villa'), ('PLOT', 'Plot / Land'), ('OFFICE', 'Commercial Office'), ('SHOP', 'Shop / Showroom')], max_length=100),
        ),
    ]
